Document: libfyba
Title: Debian libfyba Manual
Author: <insert document author here>
Abstract: This manual describes what libfyba is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfyba/libfyba.sgml.gz

Format: postscript
Files: /usr/share/doc/libfyba/libfyba.ps.gz

Format: text
Files: /usr/share/doc/libfyba/libfyba.text.gz

Format: HTML
Index: /usr/share/doc/libfyba/html/index.html
Files: /usr/share/doc/libfyba/html/*.html
